version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Context should point to the backend directory
    command: uvicorn main:app --host 0.0.0.0 --port 8000  # main.py should be in /app inside the container
    working_dir: /app  # Set the working directory to /app
    volumes:
      - ./backend:/app  # Mount the backend directory as /app inside the container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=db
      - DATABASE=items-db
      - DATABASE_USR=user
      - DATABASE_PWD=password

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=items-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data:
