
# Add items to Database
POST https://jhpebgypsc.us-east-1.awsapprunner.com/items/ HTTP/1.1
Content-type: application/json; charset=utf8
X-User: 1

{
  "name": "Fish",
  "description": "Cat fish",
  "price": 10,
  "in_stock": true
}

POST http://localhost:8000/items HTTP/1.1
Content-type: application/json; charset=utf8
X-User: 1

{
  "name": "Dog",
  "description": "Black god",
  "price": 20,
  "in_stock": false
}

POST http://localhost:8000/items HTTP/1.1
Content-type: application/json; charset=utf8
X-User: 1

{
  "name": "Pig",
  "description": "Fat pig",
  "price": 30,
  "in_stock": true
}

# Get all items
GET http://localhost:8000/items HTTP/1.1

# Get item by id
GET http://localhost:8000/items/1 HTTP/1.1

# DELETE item by id
DELETE http://localhost:8000/items/1 HTTP/1.1

# Update an item
PUT http://localhost:8000/items/4 HTTP/1.1
Content-type: application/json; charset=utf8
X-User: 1

{
  "name": "Pig",
  "description": "Fat pig",
  "price": 390,
  "in_stock": false
}
