name: github actions
on:
  push:
    branches:
      - main
jobs:
  Demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps
    steps:
      - id: "CheckoutRepo"
        name: Checkout repository
        uses: actions/checkout@v4
